// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fllopychqjjxpfkzrhzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbG9weWNocWpqeHBma3pyaHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTk5ODgsImV4cCI6MjA2ODk3NTk4OH0.iMHtaMA9oO198BBCllxnUZ6QlKclRvs8-GrXH5TxD58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});